export const NEW_DATA = 'NEW_DATA';
export const UPDATE_SITE_PREF = 'UPDATE_SITE_PREF';
export const UPDATE_SITE_INFO = 'UPDATE_SITE_INFO';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
